service: dio-live-serverless-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:us-east-1:701382444938:table/ItemTableNew

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
inserItem:
  handler: src/insertitem.handler
  events:
    - http:
        path: /item
        method: post
fetchItems:
  handler: src/fetchitems.handler
  events:
    - http:
        path: /items
        method: get
fetchItem:
  handler: src/fetchitem.handler
  events:
    - http:
        path: /items{id}
        method: get
updateItem:
  handler: src/updateitem.handler
  events:
    - http:
        path: /items{id}
        method: put        

resources:
  Resourcers:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
        Properties:
          TableName: ItemTableNew
            BillingMode: PAY_PER_REQUEST
              AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
              KeySchema:
                - AttributeName: id
                KeyType: HASH